# Generated by Django 5.0.1 on 2024-01-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=100, verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100, verbose_name='Инвентарный номер')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('country_of_manufacture', models.CharField(max_length=100, verbose_name='Страна производителя')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('model', models.CharField(max_length=100, verbose_name='Модель техники')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.employee', verbose_name='Закрепленный сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Остаток')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.technique', verbose_name='Техника')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse', verbose_name='Название склада')),
            ],
        ),
    ]
